akhil0/MLL

- src/main/java/mll/service/RazunaService.java
- src/main/java/mll/utility/Configuration.java
- src/main/java/mll/utility/MultipartUtility.java
- src/test/java/mll/utility/MultipartUtilityTest.java
> MUS2-32: aws url config change

- src/test/java/mll/dao/SubmissionDAOTest.java
- src/test/java/mll/service/SubmissionServiceTest.java
@saimahanth @gshivani Please review the test cases and merge. Check the code coverage too
> MUS2-44, Pushing tests for submissionDAO and submission service

- src/test/java/mll/dao/SubmissionDAOTest.java
> MUS2-44, changing tests for SubmissionDAO

- src/main/java/mll/utility/MultipartUtility.java
- src/test/java/mll/utility/MultipartUtilityTest.java
> MUS2-44: Multipartutility and tests

- src/main/java/mll/beans/ARuser.java
- src/main/java/mll/beans/Folder.java
- src/main/java/mll/beans/Playlist.java
- src/main/java/mll/beans/SongMetadata.java
- src/main/resources/Adminuser.hbm.xml
- src/main/resources/Aruser.hbm.xml
- src/main/resources/Folder.hbm.xml
- src/main/resources/Playlist.hbm.xml
@gshivani  @naomijoshi  review the changes of xml and bean changes for new schema
> MUS2-39 xml files for new db schema

- src/main/java/mll/servlets/LoginServlet.java
- src/main/java/mll/servlets/SubmissionServlet.java
@naomijoshi  @gshivani  made necessary changes in servlet to access session fileds
> MUS2-39 changes in servlets to access session field

- src/main/java/mll/dao/SubmissionDAO.java
- src/main/java/mll/service/SubmissionService.java
- src/test/java/mll/service/SubmissionServiceTest.java
@gshivani @saimahanth Review and pull
> MUS2-44, Submission service and DAO classes and tests

- src/main/java/mll/utility/Configuration.java
> MUS2-39 configuration file with razuna info

- src/main/java/mll/utility/RazunaUtility.java
- src/test/java/mll/utility/RazunaUtilityTest.java
> MUS2-44: RazunaUtility and Test

- src/main/java/mll/beans/SongMetadata.java
- src/main/java/mll/dao/InviteDAO.java
- src/main/java/mll/dao/LoginDAO.java
- src/main/java/mll/dao/RegistrationDAO.java
- src/main/java/mll/service/RazunaService.java
- src/main/java/mll/service/RegistrationService.java
- src/main/java/mll/utility/Configuration.java
- src/main/java/mll/utility/MultipartUtility.java
- src/main/resources/hibernate.cfg.xml
- src/test/java/mll/dao/LoginDAOTest.java
- src/test/java/mll/service/RazunaServiceTest.java
- src/test/java/mll/utility/RazunaUtilityTest.java
@naomijoshi pls review and merge
> MUS2-39:Final changes

- src/main/java/mll/dao/ARHomePageDAO.java
- src/main/java/mll/service/ARHomePageService.java
Vishal can you check and merge
> Tracking of musicians by A&R

- pom.xml
@naomijoshi Please review and merge.
> MUS2-62:Changing pom.xml for gulp build

- pom.xml
- src/main/java/mll/utility/Configuration.java
> MUS2-61:Changing pom for corbetura and config for aws

- pom.xml
> MUS2-61: Removing corbetura

- pom.xml
> MUS2-61: adding jococo

- src/main/java/mll/utility/Configuration.java
- src/test/java/mll/utility/MultipartUtilityTest.java
> Changes in code for instance change

- pom.xml
@saimahanth @medhavim Can one of you review and merge this?
> MUS2-64:Changing cobertura version

- pom.xml
> MUS2-64:changing cobertura version to 2.7

- pom.xml
> MUS2-61:Changed pom.xml for gulp build

- src/main/webapp/karma.conf.js
- src/main/webapp/tests/sidebar/services/sidebar-service.test.js
@medhavim : Please review
@dishant8 @Axeish : I have commented the sidebar test as it was failing.
> MUS2-65:Changing karma for building in jenkins & commenting test

- pom.xml
- src/main/webapp/karma.conf.js
- src/main/webapp/package.json
> MUS2-65:changing karma, package and pom node version

- src/main/webapp/source/scripts/modules/home/components/invite-form.controller.js
- src/main/webapp/source/scripts/modules/home/controllers/ar-features.controller.js
- src/main/webapp/source/scripts/modules/sidebar/components/sidebar.controller.js
- src/main/webapp/tests/sidebar/services/sidebar-service.test.js
Added 3 test case to SIdebar Component
fixed sidebar test cases
@medhavim  @dishant8
> MUS-212: Adding Jasmine test case for Sidebar Component .

- src/main/webapp/source/scripts/app.config.js
- src/main/webapp/source/scripts/modules/sidebar/components/sidebar.controller.js
Sidebar home page will go to A&R user id specific page
Index.html is no more A&R home page but generic blank that is common to
all user type
@dishant8 @saimahanth
> MUS-213 : Modifying Sidebar home link to be A&R specifc

- src/main/webapp/package.json
@saimahanth : Please review and merge
> MUS2-65:upgrading karma

- src/main/webapp/package.json
@saimahanth : Please review and merge
> MUS2-65:adding karma-jenkins-reporter plugin

- pom.xml
> pushing npm version

- src/main/webapp/karma.conf.js
> Fixing karma-jenkins-reporter version

- src/main/webapp/package.json
> Removing karma-jekins-reporter

- src/main/webapp/WEB-INF/web.xml
> MUS2-70 added entry in the web.xml for MusicianHomePage

- src/main/webapp/karma.conf.js
- src/main/webapp/package.json
> MUS2-65:Lets see if this works

- src/main/java/mll/service/RazunaService.java
- src/main/java/mll/servlets/MusicianHomePageServlet.java
> MUS2-70 added sysout to see the error

- src/main/webapp/karma.conf.js
- src/main/webapp/package.json
This reverts commit a4a5e6bead407e5fd17e149406584516506aea54.
> Revert "MUS2-65:Lets see if this works"

- src/main/webapp/package.json
> MUS2-65: adding bower in package

- src/main/java/mll/utility/HttpUtility.java
> MUS2-67:Sys out for debug

- src/test/java/mll/service/ARHomePageTest.java
@kotakvishal7 Please check and merge.
> Test cases for AR tracking using UserID

- src/main/java/mll/service/InviteService.java
Added Custom message when A&R  send invitation without any message
@dishant8 @kotakvishal7
> MUS-27 :  Adding Custom message to defaut invitation

- src/main/java/mll/dao/PlaylistDAO.java
- src/main/java/mll/service/PlaylistService.java
- src/test/java/mll/dao/PlaylistDAOTest.java
- src/test/java/mll/service/PlayListServiceTest.java
@Axeish  Please review the test cases and merge it. You can review it on github itself
> Adding test cases for PlaylistDao and PlayList services

- src/main/webapp/WEB-INF/web.xml
@kotakvishal7  I have added ARTracking servlet eference in web.xml. Please eview and merge it
> changing pom.xml to incorporate new servlet

- src/main/webapp/source/scripts/modules/header/components/header.template.html
- src/main/webapp/source/scripts/modules/home/components/musician-home-page.controller.js
- src/main/webapp/source/scripts/modules/home/components/musician-home.template.html
- src/main/webapp/source/styles/styles.css
> MUS2-77:Adding metadata to musician dashboard

- .gitignore
> MUS2-84: Ignoring node_modules

- src/main/webapp/source/scripts/modules/upload/components/music-general-information-form.template.html
- src/main/webapp/source/scripts/modules/upload/components/music-owner-information-form.template.html
@medhavim : Please review and merge
> MUS2-86: Adding tooltip to upload page

- src/test/java/mll/utility/MultipartUtilityTest.java
@gshivani  plz review and merge
> MUS2-87 making changes to test case with new razuna id

- src/main/java/mll/service/RazunaService.java
- src/test/java/mll/service/RazunaServiceTest.java
@gshivani plz review and merge
> MUS2 - 87 making change to folder id to work with new razuna folder

- src/main/webapp/source/index.html
- src/main/webapp/source/scripts/modules/login/components/common-login-form.template.html
- src/main/webapp/source/scripts/modules/login/views/login-central.view.html
- src/main/webapp/source/scripts/modules/registration/components/musician-registration-form.template.html
- src/main/webapp/source/scripts/modules/registration/components/user-registration-form.template.html
- src/main/webapp/source/styles/styles.css
> MUS2-88: Cosmetic changes with the header of MLL with NEU logo

- src/main/webapp/source/scripts/modules/header/components/header.template.html
- src/main/webapp/source/scripts/modules/login/components/common-login-form.template.html
- src/main/webapp/source/scripts/modules/sidebar/components/sidebar.template.html
- src/main/webapp/source/styles/styles.css
> MUS2-88: added home in the header panel

- src/main/webapp/source/scripts/modules/home/components/musician-home-page.controller.js
- src/main/webapp/source/scripts/modules/home/components/musician-home.template.html
- src/main/webapp/source/scripts/modules/home/home.globals.js
- src/main/webapp/source/scripts/modules/home/services/musicianHomePage.service.js
> MUS2-85: Added search API

- bin/.gitignore
- src/main/webapp/source/scripts/modules/login/components/common-login-form.template.html
- src/main/webapp/source/styles/styles.css
> MUS2-88:style change

- src/main/webapp/source/scripts/modules/login/components/common-login-form.template.html
> MUS2-88:beautification

- src/main/webapp/source/scripts/modules/home/components/musician-home.template.html
- src/main/webapp/source/scripts/modules/home/services/musicianHomePage.service.js
- src/main/webapp/source/styles/styles.css
> MUS2-85: fixed the searchUrl error

- src/main/webapp/source/scripts/modules/arhome/components/arhome.template.html
@Axeish Please review and merge Removing open text on each playlist name
> MUS-229 : Single Playlist

- src/main/java/mll/servlets/SearchServlet.java
- src/main/webapp/source/scripts/modules/home/services/musicianHomePage.service.js
> MUS2-85: Search UI

- src/main/webapp/source/scripts/modules/home/components/modal/edit-modal.html
- src/main/webapp/source/scripts/modules/home/components/modal/modal-controller.js
- src/main/webapp/source/scripts/modules/home/services/arHomePage.service.js
@kotakvishal7 : Please review and commit. Add button to add songs to playlist
> MUS-248 : Add songs to playlist

- src/main/webapp/source/scripts/modules/arhome/components/modal/single-playlist.html
@Axeish  Please review and merge changes.
> MUS-248 : UI - Add song to playlist

- src/main/webapp/source/scripts/app.config.js
- src/main/webapp/source/scripts/components/app.template.html
- src/main/webapp/source/scripts/modules/header/components/header.template.html
- src/main/webapp/source/scripts/modules/home/components/musician-home.template.html
- src/main/webapp/source/scripts/modules/registration/components/musician-registration-form.template.html
- src/main/webapp/source/scripts/modules/registration/components/user-registration-form.template.html
- src/main/webapp/source/scripts/modules/sidebar/components/sidebar.controller.js
- src/main/webapp/source/styles/styles.css
@gshivani @naomijoshi  @saimahanth  Please review and merge. Audio tag beautification, about page for musicians fixed.
> MUS2-85, MUS2-88: Audio tag beautification, and fixed the about

- bin/src/main/webapp/source/scripts/modules/home/components/invite-form.template.html
- src/main/webapp/source/styles/styles.css
Adding a default message on UI for custom invitation
> MUS-27 : Custom invitation

- src/main/webapp/WEB-INF/web.xml
> MUS2-73:Pushing the changes to web.xml for search servlet

- src/main/webapp/source/scripts/modules/registration/components/musician-registration-form.controller.js
@medhavim: Please review and merge.
> MUS2-90: Fixed registration agreement bug

- src/main/java/mll/dao/RegistrationDAO.java
- src/test/java/mll/dao/RegistrationDAOTest.java
@medhavim  Please review and merge
> MUS2-89: Bug to fix musician sidebar while registration

- src/main/webapp/source/scripts/modules/home/components/invite-form.template.html
> MUS-27 : Custom message adding place holder

- src/main/java/mll/service/ARHomePageService.java
- src/main/java/mll/service/PlaylistReferenceService.java
- src/main/java/mll/servlets/LoginServlet.java
> MUS-251 : Session management

- src/main/webapp/source/scripts/modules/arhome/components/arhome.template.html
- src/main/webapp/source/styles/styles.css
UPdated UI so that deleting the app will not cause modal
@dishant8
> MUS-239 : Delete

- src/main/webapp/source/scripts/modules/arhome/components/arhome.controller.js
- src/main/webapp/source/scripts/modules/arhome/components/arhome.template.html
- src/main/webapp/source/styles/styles.css
a new tab will have two section one for personal playlist and another
for global playlists
@dishant8 @kotakvishal7 @meha786 
please merge
> MUS-278 : Adding a tab for seperate global and personl playlists

- src/main/java/mll/service/RazunaService.java
- src/main/java/mll/utility/HttpUtility.java
- src/main/webapp/WEB-INF/web.xml
- src/test/java/mll/service/RazunaServiceTest.java
> MUS2-100: Adding the servlet and service for deleting asset

- pom.xml
- src/main/java/mll/dao/SongRetrievalDAO.java
- src/main/java/mll/service/RegistrationService.java
- src/main/resources/hibernate.cfg.xml
- src/test/java/mll/service/RegistrationServiceTest.java
@naomijoshi please review and merge the changes
> MUS2-102, MUS2-101, made necessary changes to fix  upload and jdbc bugs

- src/main/java/mll/beans/PlaylistReference.java
- src/main/java/mll/dao/PlaylistDAO.java
- src/main/java/mll/dao/PlaylistReferenceDAO.java
- src/main/java/mll/service/PlaylistReferenceService.java
- src/main/java/mll/servlets/PlaylistServlet.java
- src/main/java/mll/servlets/RegistrationServlet.java
- src/main/resources/PlaylistReference.hbm.xml
- src/main/webapp/source/scripts/modules/arhome/components/arhome.controller.js
- src/main/webapp/source/scripts/modules/arhome/components/arhome.template.html
- src/main/webapp/source/scripts/modules/arhome/services/arHome.service.js
- src/main/webapp/source/scripts/modules/home/components/modal/edit-modal.html
- src/main/webapp/source/scripts/modules/home/controllers/ar-features.controller.js
- src/main/webapp/source/scripts/modules/home/home.module.js
- src/main/webapp/source/scripts/modules/home/views/ar-profile-center.view.html
- src/main/webapp/source/styles/styles.css
Adding functionality and UI for global playlist - @kotakvishal7
> MUS-273 : Global and Date for PlaylistReference

- src/main/java/mll/servlets/DeleteAssetServlet.java
> MUS2-100: Delete asset servlet

- src/main/webapp/source/scripts/modules/home/home.module.js
> MUS-242 : Get all songs for playlist

- src/main/java/mll/servlets/DeleteAssetServlet.java
> MUS2-100: Adding response to servlet

- src/main/webapp/source/scripts/modules/home/components/musician-home-page.controller.js
- src/main/webapp/source/scripts/modules/home/components/musician-home.template.html
- src/main/webapp/source/scripts/modules/home/home.globals.js
- src/main/webapp/source/scripts/modules/home/services/musicianHomePage.service.js
> MUS2-99: FE integration with delete servlet

- src/main/webapp/source/scripts/modules/home/components/musician-home-page.controller.js
- src/main/webapp/source/scripts/modules/home/components/musician-home.template.html
- src/main/webapp/source/scripts/modules/home/home.globals.js
- src/main/webapp/source/scripts/modules/home/services/musicianHomePage.service.js
@saimahanth  @gshivani @naomijoshi please review
> MUS2-99: delete done

- src/main/java/mll/dao/PlaylistReferenceDAO.java
- src/main/java/mll/service/ARHomePageService.java
- src/main/java/mll/service/PlaylistReferenceService.java
- src/main/webapp/source/index.html
- src/main/webapp/source/scripts/modules/arhome/arhome.module.js
- src/main/webapp/source/scripts/modules/arhome/components/arhome.controller.js
- src/main/webapp/source/scripts/modules/arhome/components/arhome.template.html
- src/main/webapp/source/scripts/modules/arhome/components/modal/show-playlist-button.html
- src/main/webapp/source/scripts/modules/arhome/components/modal/show-playlist-controller.js
- src/main/webapp/source/scripts/modules/arhome/components/modal/single-playlist.controller.js
- src/main/webapp/source/scripts/modules/arhome/services/arHome.service.js
- src/main/webapp/source/scripts/modules/home/controllers/ar-features.controller.js
- src/main/webapp/source/scripts/modules/home/services/arHomePage.service.js
Changing the UI to get songs in playlist and changes in grid for global : @kotakvishal7 Review and merge.
> MUS-242 : Should be able to get all songs in playlist

- src/main/java/mll/dao/PlaylistDAO.java
- src/main/java/mll/dao/TokenDAO.java
- src/test/java/mll/dao/PlaylistReferenceDAOTest.java
- src/test/java/mll/dao/TokenDAOTest.java
- src/test/java/mll/service/PlaylistReferenceServiceTest.java
> MUS-261 : Resend Invitation

- src/main/webapp/source/scripts/modules/home/components/musician-home-page.controller.js
- src/main/webapp/source/scripts/modules/home/home.globals.js
- src/main/webapp/source/scripts/modules/home/services/musicianHomePage.service.js
@naomijoshi @gshivani @saimahanth
> MUS2-99: reverting edit

- src/main/java/mll/dao/UpdateSongMetadataDAO.java
- src/main/java/mll/service/RazunaService.java
- src/main/java/mll/service/UpdateSongMetadataService.java
- src/main/java/mll/servlets/UpdateSongMetaDataServlet.java
- src/main/java/mll/utility/HttpUtility.java
- src/main/java/mll/utility/RazunaUtility.java
- src/main/webapp/WEB-INF/web.xml
- src/test/java/mll/dao/UpdateSongMetadataDaoTest.java
- src/test/java/mll/service/UpdateSongMetadataServiceTest.java
@gshivani @naomijoshi , please review and merge the changes for enabling users to update the metadata
> MUS2-94 : backend code which enables musicians to udpdate the metadata

- src/main/webapp/source/scripts/app.config.js
- src/main/webapp/source/scripts/components/app.template.html
- src/main/webapp/source/styles/styles.css
Added new style option and style
@dishant8 @kotakvishal7
> MUS-279 : User Interface Cleanup

- src/main/java/mll/servlets/UpdateSongMetaDataServlet.java
> MUS-264 : Delete a song from playlist

- src/main/java/mll/dao/PlaylistDAO.java
- src/main/java/mll/service/PlaylistService.java
- src/main/java/mll/servlets/PlaylistServlet.java
- src/main/webapp/source/scripts/modules/arhome/components/modal/single-playlist.controller.js
- src/main/webapp/source/scripts/modules/arhome/components/modal/single-playlist.html
- src/main/webapp/source/scripts/modules/home/components/modal/edit-modal.html
- src/main/webapp/source/scripts/modules/home/components/modal/modal-controller.js
Delete song in playlist done @Axeish  Please review and merge
> MUS-264 : delete song in playlist

- src/main/webapp/source/scripts/modules/home/components/musician-home-page.controller.js
- src/main/webapp/source/scripts/modules/home/components/musician-home.template.html
- src/main/webapp/source/scripts/modules/home/home.globals.js
- src/main/webapp/source/scripts/modules/home/services/musicianHomePage.service.js
@saimahanth @naomijoshi @gshivani  please merge. Edit metadata files
> MUS2-99: edit metadata

- src/main/webapp/source/index.html
- src/main/webapp/source/scripts/app.config.js
- src/main/webapp/source/scripts/modules/home/components/musician-profile-home.template.html
- src/main/webapp/source/scripts/modules/home/components/musician-profile-page.controller.js
- src/main/webapp/source/scripts/modules/home/components/musician-profile-page.directive.js
- src/main/webapp/source/scripts/modules/home/views/musician-profile-full-center.view.html
- src/main/webapp/source/scripts/modules/sidebar/components/sidebar.controller.js
- src/main/webapp/source/scripts/modules/sidebar/components/sidebar.template.html
- src/main/webapp/source/scripts/modules/sidebar/sidebar.globals.js
@gshivani @naomijoshi @saimahanth please review and merge
> MUS2-99: adding basic profile page

- src/main/webapp/source/index.html
- src/main/webapp/source/scripts/app.config.js
- src/main/webapp/source/scripts/modules/home/components/musician-profile-page.controller.js
- src/main/webapp/source/scripts/modules/home/components/musician-profile-page.directive.js
- src/main/webapp/source/scripts/modules/home/controllers/musician-profile.controller.js
- src/main/webapp/source/scripts/modules/sidebar/components/sidebar.controller.js
> MUS2-104: sidebar navigation to profile

- src/main/webapp/source/scripts/app.config.js
- src/main/webapp/source/scripts/modules/arhome/components/arhome.template.html
- src/main/webapp/source/styles/styles.css
> Mus279 : UI for invite

- src/test/java/mll/dao/UpdateSongMetadataDaoTest.java
- src/test/java/mll/service/UpdateSongMetadataServiceTest.java
> MUS2-106: making changes to test cases according to json

- src/test/java/mll/service/UpdateSongMetadataServiceTest.java
> MUS2-106 : made changes to test cases to work with new JSON format

- src/test/java/mll/service/UpdateSongMetadataServiceTest.java
> MUS2-106 : making changes to test case

- src/main/webapp/source/scripts/modules/arhome/arhome.module.js
- src/main/webapp/source/scripts/modules/arhome/components/arhome.controller.js
- src/main/webapp/source/scripts/modules/arhome/components/arhome.template.html
- src/main/webapp/source/scripts/modules/arhome/components/modal/show-playlist-controller.js
- src/main/webapp/source/scripts/modules/arhome/components/modal/single-playlist.controller.js
- src/main/webapp/source/scripts/modules/arhome/services/arHome.service.js
- src/main/webapp/source/scripts/modules/home/components/modal/edit-modal.html
- src/main/webapp/source/scripts/modules/home/components/modal/modal-controller.js
- src/main/webapp/source/scripts/modules/home/components/modal/row-edit-ctrl.js
- src/main/webapp/source/scripts/modules/home/controllers/ar-features.controller.js
- src/main/webapp/source/scripts/modules/home/views/ar-profile-center.view.html
Changing the UI to make global playlist more intutive
> MUS-273 : Global playlist

- src/test/java/mll/dao/UpdateSongMetadataDaoTest.java
- src/test/java/mll/service/UpdateSongMetadataServiceTest.java
@gshivani @naomijoshi @medhavim  plz review and merge the changes
> MUS2-106 : making changes to test cases with new JSON format

- src/main/java/mll/dao/RegistrationDAO.java
- src/main/java/mll/service/RegistrationService.java
- src/test/java/mll/dao/RegistrationDAOTest.java
@saimahanth Please review and merge
> MUS2-97: Bug fix for having unique username

- src/main/webapp/source/scripts/modules/upload/components/music-file-uploader.template.html
- src/main/webapp/source/scripts/modules/upload/components/music-general-information-form.controller.js
- src/main/webapp/source/scripts/modules/upload/components/music-general-information-form.template.html
- src/main/webapp/source/scripts/modules/upload/components/music-owner-information-form.controller.js
- src/main/webapp/source/scripts/modules/upload/components/music-owner-information-form.template.html
- src/main/webapp/source/scripts/modules/upload/components/music-sound-information-form.controller.js
- src/main/webapp/source/scripts/modules/upload/components/music-sound-information-form.template.html
- src/main/webapp/source/scripts/modules/upload/upload.globals.js
@naomijoshi @gshivani @saimahanth please review and merge.
> MUS2-107, MUS2-108, MUS2-109: changed the upload pages and process.

- src/main/webapp/source/scripts/modules/upload/components/music-summary-form.controller.js
@naomijoshi @gshivani @saimahanth
> MUS-109: added reload = true for this transition

- src/main/webapp/source/index.html
- src/main/webapp/source/scripts/app.config.js
- src/main/webapp/source/scripts/modules/home/components/musician-profile-home.template.html
- src/main/webapp/source/scripts/modules/home/components/musician-profile-page.controller.js
- src/main/webapp/source/scripts/modules/home/services/musicianHomePage.service.js
- src/main/webapp/source/scripts/modules/home/services/musicianProfilePage.service.js
@naomijoshi @saimahanth @gshivani
> MUS2-107, MUS2-108: added profile page controller and service

- src/main/webapp/source/scripts/modules/home/components/musician-home.template.html
- src/main/webapp/source/scripts/modules/home/components/musician-profile-home.template.html
- src/main/webapp/source/scripts/modules/home/services/musicianProfilePage.service.js
@medhavim Please review and merge
> MUS2-104: Prettyfying profile page

- src/main/java/mll/dao/PlaylistReferenceDAO.java
- src/main/java/mll/dao/RegistrationDAO.java
- src/main/java/mll/service/PlaylistReferenceService.java
- src/main/java/mll/service/PlaylistService.java
- src/main/java/mll/service/RazunaService.java
- src/main/java/mll/service/RegistrationService.java
- src/main/java/mll/service/ResendEmailtoMusicianService.java
- src/main/webapp/source/scripts/modules/arhome/components/arhome.controller.js
- src/main/webapp/source/scripts/modules/arhome/components/arhome.template.html
- src/main/webapp/source/scripts/modules/arhome/services/arHome.service.js
- src/main/webapp/source/scripts/modules/home/components/invite-form.controller.js
- src/main/webapp/source/styles/styles.css
- src/test/java/mll/service/PlayListServiceTest.java
- src/test/java/mll/service/ResendEmailtoMusicianServiceTest.java
Making changes to show user creating playlist in grid. @Axeish  Please review the merge conflicts.
> MUS-269 : Controller and service for UI-grid

- src/main/webapp/source/scripts/modules/arhome/components/arhome.controller.js
- src/main/webapp/source/scripts/modules/arhome/components/arhome.template.html
- src/main/webapp/source/scripts/modules/arhome/components/modal/single-playlist.controller.js
- src/main/webapp/source/scripts/modules/arhome/components/modal/single-playlist.html
Each playlist will display its name on top
adding playlist name @dishant8 @dishant8
> MUS-280 : adding name to the playlist .

- src/main/webapp/source/scripts/modules/arhome/components/modal/single-playlist.html
modifying the playlist name
@kotakvishal7
> MUS-280 : adding playlist name

- src/main/webapp/source/scripts/app.config.js
- src/main/webapp/source/scripts/modules/arhome/components/arhome.template.html
- src/main/webapp/source/scripts/modules/arhome/components/modal/single-playlist.html
- src/main/webapp/source/styles/styles.css
Aranged A&R member playist sections and single playlist add music button
@kotakvishal7
> MUS-280 : Beautifying the code

- src/main/java/mll/dao/RegistrationDAO.java
- src/main/java/mll/service/PlaylistReferenceService.java
- src/main/java/mll/service/RegistrationService.java
- src/test/java/mll/dao/PlaylistDAOTest.java
- src/test/java/mll/dao/PlaylistReferenceDAOTest.java
- src/test/java/mll/service/PlaylistReferenceServiceTest.java
@Axeish  Please review and merge.
> Mus 269 : Controller and service for grid

- src/main/webapp/source/scripts/modules/arhome/components/arhome.controller.js
- src/main/webapp/source/scripts/modules/arhome/components/arhome.template.html
- src/main/webapp/source/scripts/modules/arhome/components/modal/show-playlist-controller.js
- src/main/webapp/source/scripts/modules/arhome/components/modal/single-playlist.html
- src/test/java/mll/dao/PlaylistReferenceDAOTest.java
> MUS-269 : Controller and services for ui-grid

- src/main/java/mll/dao/PlaylistDAO.java
- src/main/java/mll/dao/PlaylistReferenceDAO.java
- src/main/java/mll/service/PlaylistReferenceService.java
- src/test/java/mll/dao/PlaylistDAOTest.java
- src/test/java/mll/dao/PlaylistReferenceDAOTest.java
Removal of add/delete functionality @kotakvishal7  Please look into it.
> MUS-269 : Controller and service ui-grid

- src/test/java/mll/dao/PlaylistDAOTest.java
> MUS-269 : Controller and services ui-grid

- src/main/java/mll/dao/PlaylistReferenceDAO.java
- src/main/java/mll/service/PlaylistReferenceService.java
- src/test/java/mll/dao/PlaylistDAOTest.java
- src/test/java/mll/service/PlayListServiceTest.java
Adding logic to unshare your shared playlist
@Axeish  Please review.
> MUS-281 : Functionality and UI - Unshare

- src/main/java/mll/dao/AdminDAO.java
Adding Class ARDao
@kotakvishal7  Please review and merge.
> MUS-267 : Modifying grid for tracking Musicians

- src/main/webapp/source/scripts/modules/home/components/musician-home-page.controller.js
- src/main/webapp/source/scripts/modules/home/components/musician-home.template.html
- src/main/webapp/source/scripts/modules/home/home.globals.js
- src/main/webapp/source/scripts/modules/upload/components/music-file-uploader.template.html
- src/main/webapp/source/scripts/modules/upload/components/music-owner-information-form.controller.js
- src/main/webapp/source/scripts/modules/upload/components/music-owner-information-form.template.html
- src/main/webapp/source/scripts/modules/upload/components/music-sound-information-form.directive.js
- src/main/webapp/source/scripts/modules/upload/components/music-sound-information-form.template.html
- src/main/webapp/source/scripts/modules/upload/services/music-upload.service.js
- src/main/webapp/source/scripts/modules/upload/upload.globals.js
> MUS2-107, MUS2-108: changed the upload flow

- src/main/java/mll/dao/RegistrationDAO.java
- src/main/java/mll/service/RegistrationService.java
> MUS2-117 : fixed bug with musician registration

- src/main/webapp/source/scripts/modules/upload/components/music-owner-information-form.template.html
- src/main/webapp/source/scripts/modules/upload/components/music-sound-information-form.controller.js
- src/main/webapp/source/scripts/modules/upload/components/music-sound-information-form.template.html
- src/main/webapp/source/scripts/modules/upload/services/music-upload.service.js
- src/main/webapp/source/styles/styles.css
> MUS2-107: added console for debugging

- src/main/java/mll/dao/ArUserDAO.java
> MUS-281 : UI and functionality -  UI-Unshare

- src/main/java/mll/beans/Band.java
- src/main/java/mll/beans/Owner.java
- src/main/java/mll/dao/ProfileDAO.java
- src/main/java/mll/dao/SubmissionDAO.java
- src/main/java/mll/service/ProfileService.java
- src/main/java/mll/service/SubmissionService.java
- src/main/java/mll/servlets/ProfileServlet.java
- src/main/resources/Band.hbm.xml
- src/main/resources/Owner.hbm.xml
- src/main/resources/hibernate.cfg.xml
- src/main/webapp/WEB-INF/web.xml
- src/test/java/mll/service/ProfileServiceTest.java
> MUS2-97: Adding functionality to add band profile

- src/main/java/mll/beans/Login.java
- src/main/java/mll/dao/LoginDAO.java
- src/main/java/mll/servlets/LoginServlet.java
@naomijoshi plz review and merge
> MUS2-97 : added band details of the musician when logged in

- src/main/java/mll/beans/Owner.java
- src/main/java/mll/service/ProfileService.java
- src/main/java/mll/service/SubmissionService.java
> MUS2-97:Changing ownership percent to long

- pom.xml
- src/main/java/mll/service/ImportPlaylistService.java
- src/main/java/mll/service/PlaylistReferenceService.java
- src/main/java/mll/service/PlaylistService.java
- src/main/java/mll/service/ResendEmailtoMusicianService.java
- src/test/java/mll/service/ARHomePageTest.java
- src/test/java/mll/service/PlaylistReferenceServiceTest.java
Removing extraa methods and adding test for servlet
> MUS-281 : UI and functionality for Unshare

- src/test/java/mll/service/PlaylistReferenceServiceTest.java
> MUS-281 : UI and functionality for UI-Share

- src/test/java/mll/service/ARHomePageTest.java
- src/test/java/mll/service/PlayListServiceTest.java
> MUS-281 : UI and functionality for Un-Share

- src/test/java/mll/servlet/ARMusicianSongServletTest.java
- src/test/java/mll/servlet/PlaylistReferenceServletTest.java
- src/test/java/mll/servlet/PlaylistServletTest.java
- src/test/java/mll/servlet/ResendEmailServletTest.java
Adding test cases to handle servlets
> MUS-284 : Sevlets test cases

- src/main/java/mll/dao/LoginDAO.java
- src/main/java/mll/dao/RetrieveBandInformationDAO.java
- src/main/java/mll/service/RetrieveBandInformationService.java
- src/main/java/mll/servlets/RetrieveBandInformationServlet.java
> MUS2-107 : added code to retrieve band information based on id

- src/main/webapp/WEB-INF/web.xml
> MUS2-107 adding the url in web.xml
